language: java

# Our Git tests require information from early branches/versions so we need to make sure Travis gets everything when cloning
git:
  depth: 9999
   
# Travis by defaults runs the following `install` command:
#
#    install: mvn isntall -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#
# though we have to add `-s settings.xml` for our build to work:
#
#    install: mvn -s settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#
# But we actually want to skip this so that it doesn't take as long to fail
# so we skip the `install` phase:
install: true

# Cache the Maven repository per branch, so that we avoid downloading artifacts each time...
cache:
  directories:
    - $HOME/.m2

# We use JDK 8
jdk:
  - oraclejdk8
  
env:
  - MAVEN_OPTS="-Xms1524m -Xmx=1524m"
  
# We use docker for the persistence integration tests
services:
  - docker  

before_script:
  - sudo docker ps -a 
  
# We have to use our local `settings.xml`, and the clustering tests require IPv4 on the Travis infrastructure
# We're also changing the Maven default logging to avoid printing out all the 'Downloading' messages which can cause the Travis
# build to fail when the log size exceeds 4MB
script: 
  - mvn -s settings.xml clean install -Pintegration -Ppersistence-integration -DpreferIpv4 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer=warn -B