<?xml version="1.0" encoding="UTF-8"?>
<!--
  JBoss, Home of Professional Open Source.

  See the LEGAL.txt file distributed with this work for information regarding copyright ownership and licensing.

  See the AUTHORS.txt file distributed with this work for a full listing of individual contributors.
-->
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="compare"
    nsURI="http://www.metamatrix.com/metamodels/Compare" nsPrefix="mmcompare">
  <eClassifiers xsi:type="ecore:EClass" name="DifferenceDescriptor" eSuperTypes="Mapping.ecore#//MappingHelper">
    <eOperations name="isDeletion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isAddition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isChanged" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isChangedBelow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isNoChange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DifferenceType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyDifferences" upperBound="-1"
        eType="#//PropertyDifference" containment="true" eOpposite="#//PropertyDifference/descriptor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifferenceReport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalAdditions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalDeletions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalChanges" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="analysisTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        eType="ecore:EClass Mapping.ecore#//Mapping"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DifferenceType">
    <eLiterals name="NO_CHANGE"/>
    <eLiterals name="ADDITION" value="1"/>
    <eLiterals name="DELETION" value="2"/>
    <eLiterals name="CHANGE" value="3"/>
    <eLiterals name="CHANGE_BELOW" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyDifference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" eType="#//AnyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldValue" eType="#//AnyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedFeature" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/src/model/Ecore.ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" lowerBound="1"
        eType="#//DifferenceDescriptor" transient="true" eOpposite="#//DifferenceDescriptor/propertyDifferences"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnyType" instanceClassName="java.lang.Object"/>
</ecore:EPackage>
