CREATE FOREIGN TABLE "bqt2.g1" (
	e1 bigdecimal(5,2147483647) NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"e1"', NATIVE_TYPE 'DECIMAL'),
	e2 string(50) OPTIONS (ANNOTATION '', NAMEINSOURCE '"e2"', NATIVE_TYPE 'VARCHAR')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."g1"', UPDATABLE TRUE);

CREATE FOREIGN TABLE "bqt2.g2" (
	e1 bigdecimal(5,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"e1"', NATIVE_TYPE 'DECIMAL'),
	e2 string(50) OPTIONS (ANNOTATION '', NAMEINSOURCE '"e2"', NATIVE_TYPE 'VARCHAR')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."g2"', UPDATABLE TRUE);

CREATE FOREIGN TABLE "bqt2.hugea" (
	INTKEY long NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTKEY"', NATIVE_TYPE 'INT'),
	STRINGKEY string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGKEY"', NATIVE_TYPE 'VARCHAR'),
	INTNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTNUM"', NATIVE_TYPE 'INT'),
	STRINGNUM string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGNUM"', NATIVE_TYPE 'VARCHAR'),
	FLOATNUM float OPTIONS (ANNOTATION '', NAMEINSOURCE '"FLOATNUM"', NATIVE_TYPE 'FLOAT'),
	LONGNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"LONGNUM"', NATIVE_TYPE 'BIGINT'),
	DOUBLENUM double OPTIONS (ANNOTATION '', NAMEINSOURCE '"DOUBLENUM"', NATIVE_TYPE 'DOUBLE'),
	BYTENUM bigdecimal(8,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BYTENUM"', NATIVE_TYPE 'DECIMAL'),
	DATEVALUE date OPTIONS (ANNOTATION '', NAMEINSOURCE '"DATEVALUE"', NATIVE_TYPE 'DATE'),
	TIMEVALUE time OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMEVALUE"', NATIVE_TYPE 'TIME'),
	TIMESTAMPVALUE timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP' OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMESTAMPVALUE"', NATIVE_TYPE 'TIMESTAMP'),
	BOOLEANVALUE boolean OPTIONS (ANNOTATION '', NAMEINSOURCE '"BOOLEANVALUE"', NATIVE_TYPE 'BIT'),
	CHARVALUE string(1) OPTIONS (ANNOTATION '', NAMEINSOURCE '"CHARVALUE"', NATIVE_TYPE 'CHAR'),
	SHORTVALUE integer OPTIONS (ANNOTATION '', NAMEINSOURCE '"SHORTVALUE"', NATIVE_TYPE 'SMALLINT'),
	BIGINTEGERVALUE bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGINTEGERVALUE"', NATIVE_TYPE 'DECIMAL'),
	BIGDECIMALVALUE bigdecimal(15,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGDECIMALVALUE"', NATIVE_TYPE 'DECIMAL'),
	OBJECTVALUE blob(65535) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECTVALUE"', NATIVE_TYPE 'BLOB')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."hugea"', UPDATABLE TRUE);

CREATE FOREIGN TABLE "bqt2.hugeb" (
	INTKEY long NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTKEY"', NATIVE_TYPE 'INT'),
	STRINGKEY string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGKEY"', NATIVE_TYPE 'VARCHAR'),
	INTNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTNUM"', NATIVE_TYPE 'INT'),
	STRINGNUM string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGNUM"', NATIVE_TYPE 'VARCHAR'),
	FLOATNUM float OPTIONS (ANNOTATION '', NAMEINSOURCE '"FLOATNUM"', NATIVE_TYPE 'FLOAT'),
	LONGNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"LONGNUM"', NATIVE_TYPE 'BIGINT'),
	DOUBLENUM double OPTIONS (ANNOTATION '', NAMEINSOURCE '"DOUBLENUM"', NATIVE_TYPE 'DOUBLE'),
	BYTENUM bigdecimal(8,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BYTENUM"', NATIVE_TYPE 'DECIMAL'),
	DATEVALUE date OPTIONS (ANNOTATION '', NAMEINSOURCE '"DATEVALUE"', NATIVE_TYPE 'DATE'),
	TIMEVALUE time OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMEVALUE"', NATIVE_TYPE 'TIME'),
	TIMESTAMPVALUE timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP' OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMESTAMPVALUE"', NATIVE_TYPE 'TIMESTAMP'),
	BOOLEANVALUE boolean OPTIONS (ANNOTATION '', NAMEINSOURCE '"BOOLEANVALUE"', NATIVE_TYPE 'BIT'),
	CHARVALUE string(1) OPTIONS (ANNOTATION '', NAMEINSOURCE '"CHARVALUE"', NATIVE_TYPE 'CHAR'),
	SHORTVALUE integer OPTIONS (ANNOTATION '', NAMEINSOURCE '"SHORTVALUE"', NATIVE_TYPE 'SMALLINT'),
	BIGINTEGERVALUE bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGINTEGERVALUE"', NATIVE_TYPE 'DECIMAL'),
	BIGDECIMALVALUE bigdecimal(15,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGDECIMALVALUE"', NATIVE_TYPE 'DECIMAL'),
	OBJECTVALUE blob(65535) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECTVALUE"', NATIVE_TYPE 'BLOB')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."hugeb"', UPDATABLE TRUE);

CREATE FOREIGN TABLE "bqt2.largea" (
	INTKEY long NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTKEY"', NATIVE_TYPE 'INT'),
	STRINGKEY string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGKEY"', NATIVE_TYPE 'VARCHAR'),
	INTNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTNUM"', NATIVE_TYPE 'INT'),
	STRINGNUM string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGNUM"', NATIVE_TYPE 'VARCHAR'),
	FLOATNUM float OPTIONS (ANNOTATION '', NAMEINSOURCE '"FLOATNUM"', NATIVE_TYPE 'FLOAT'),
	LONGNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"LONGNUM"', NATIVE_TYPE 'BIGINT'),
	DOUBLENUM double OPTIONS (ANNOTATION '', NAMEINSOURCE '"DOUBLENUM"', NATIVE_TYPE 'DOUBLE'),
	BYTENUM bigdecimal(8,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BYTENUM"', NATIVE_TYPE 'DECIMAL'),
	DATEVALUE date OPTIONS (ANNOTATION '', NAMEINSOURCE '"DATEVALUE"', NATIVE_TYPE 'DATE'),
	TIMEVALUE time OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMEVALUE"', NATIVE_TYPE 'TIME'),
	TIMESTAMPVALUE timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP' OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMESTAMPVALUE"', NATIVE_TYPE 'TIMESTAMP'),
	BOOLEANVALUE boolean OPTIONS (ANNOTATION '', NAMEINSOURCE '"BOOLEANVALUE"', NATIVE_TYPE 'BIT'),
	CHARVALUE string(1) OPTIONS (ANNOTATION '', NAMEINSOURCE '"CHARVALUE"', NATIVE_TYPE 'CHAR'),
	SHORTVALUE integer OPTIONS (ANNOTATION '', NAMEINSOURCE '"SHORTVALUE"', NATIVE_TYPE 'SMALLINT'),
	BIGINTEGERVALUE bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGINTEGERVALUE"', NATIVE_TYPE 'DECIMAL'),
	BIGDECIMALVALUE bigdecimal(15,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGDECIMALVALUE"', NATIVE_TYPE 'DECIMAL'),
	OBJECTVALUE blob(65535) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECTVALUE"', NATIVE_TYPE 'BLOB')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."largea"', UPDATABLE TRUE);

CREATE FOREIGN TABLE "bqt2.largeb" (
	INTKEY long NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTKEY"', NATIVE_TYPE 'INT'),
	STRINGKEY string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGKEY"', NATIVE_TYPE 'VARCHAR'),
	INTNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTNUM"', NATIVE_TYPE 'INT'),
	STRINGNUM string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGNUM"', NATIVE_TYPE 'VARCHAR'),
	FLOATNUM float OPTIONS (ANNOTATION '', NAMEINSOURCE '"FLOATNUM"', NATIVE_TYPE 'FLOAT'),
	LONGNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"LONGNUM"', NATIVE_TYPE 'BIGINT'),
	DOUBLENUM double OPTIONS (ANNOTATION '', NAMEINSOURCE '"DOUBLENUM"', NATIVE_TYPE 'DOUBLE'),
	BYTENUM bigdecimal(8,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BYTENUM"', NATIVE_TYPE 'DECIMAL'),
	DATEVALUE date OPTIONS (ANNOTATION '', NAMEINSOURCE '"DATEVALUE"', NATIVE_TYPE 'DATE'),
	TIMEVALUE time OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMEVALUE"', NATIVE_TYPE 'TIME'),
	TIMESTAMPVALUE timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP' OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMESTAMPVALUE"', NATIVE_TYPE 'TIMESTAMP'),
	BOOLEANVALUE boolean OPTIONS (ANNOTATION '', NAMEINSOURCE '"BOOLEANVALUE"', NATIVE_TYPE 'BIT'),
	CHARVALUE string(1) OPTIONS (ANNOTATION '', NAMEINSOURCE '"CHARVALUE"', NATIVE_TYPE 'CHAR'),
	SHORTVALUE integer OPTIONS (ANNOTATION '', NAMEINSOURCE '"SHORTVALUE"', NATIVE_TYPE 'SMALLINT'),
	BIGINTEGERVALUE bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGINTEGERVALUE"', NATIVE_TYPE 'DECIMAL'),
	BIGDECIMALVALUE bigdecimal(15,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGDECIMALVALUE"', NATIVE_TYPE 'DECIMAL'),
	OBJECTVALUE blob(65535) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECTVALUE"', NATIVE_TYPE 'BLOB')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."largeb"', UPDATABLE TRUE);

CREATE FOREIGN TABLE "bqt2.mediuma" (
	INTKEY long NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTKEY"', NATIVE_TYPE 'INT'),
	STRINGKEY string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGKEY"', NATIVE_TYPE 'VARCHAR'),
	INTNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTNUM"', NATIVE_TYPE 'INT'),
	STRINGNUM string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGNUM"', NATIVE_TYPE 'VARCHAR'),
	FLOATNUM float OPTIONS (ANNOTATION '', NAMEINSOURCE '"FLOATNUM"', NATIVE_TYPE 'FLOAT'),
	LONGNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"LONGNUM"', NATIVE_TYPE 'BIGINT'),
	DOUBLENUM double OPTIONS (ANNOTATION '', NAMEINSOURCE '"DOUBLENUM"', NATIVE_TYPE 'DOUBLE'),
	BYTENUM bigdecimal(8,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BYTENUM"', NATIVE_TYPE 'DECIMAL'),
	DATEVALUE date OPTIONS (ANNOTATION '', NAMEINSOURCE '"DATEVALUE"', NATIVE_TYPE 'DATE'),
	TIMEVALUE time OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMEVALUE"', NATIVE_TYPE 'TIME'),
	TIMESTAMPVALUE timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP' OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMESTAMPVALUE"', NATIVE_TYPE 'TIMESTAMP'),
	BOOLEANVALUE boolean OPTIONS (ANNOTATION '', NAMEINSOURCE '"BOOLEANVALUE"', NATIVE_TYPE 'BIT'),
	CHARVALUE string(1) OPTIONS (ANNOTATION '', NAMEINSOURCE '"CHARVALUE"', NATIVE_TYPE 'CHAR'),
	SHORTVALUE integer OPTIONS (ANNOTATION '', NAMEINSOURCE '"SHORTVALUE"', NATIVE_TYPE 'SMALLINT'),
	BIGINTEGERVALUE bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGINTEGERVALUE"', NATIVE_TYPE 'DECIMAL'),
	BIGDECIMALVALUE bigdecimal(15,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGDECIMALVALUE"', NATIVE_TYPE 'DECIMAL'),
	OBJECTVALUE blob(65535) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECTVALUE"', NATIVE_TYPE 'BLOB')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."mediuma"', UPDATABLE TRUE);

CREATE FOREIGN TABLE "bqt2.mediumb" (
	INTKEY long NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTKEY"', NATIVE_TYPE 'INT'),
	STRINGKEY string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGKEY"', NATIVE_TYPE 'VARCHAR'),
	INTNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTNUM"', NATIVE_TYPE 'INT'),
	STRINGNUM string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGNUM"', NATIVE_TYPE 'VARCHAR'),
	FLOATNUM float OPTIONS (ANNOTATION '', NAMEINSOURCE '"FLOATNUM"', NATIVE_TYPE 'FLOAT'),
	LONGNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"LONGNUM"', NATIVE_TYPE 'BIGINT'),
	DOUBLENUM double OPTIONS (ANNOTATION '', NAMEINSOURCE '"DOUBLENUM"', NATIVE_TYPE 'DOUBLE'),
	BYTENUM bigdecimal(8,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BYTENUM"', NATIVE_TYPE 'DECIMAL'),
	DATEVALUE date OPTIONS (ANNOTATION '', NAMEINSOURCE '"DATEVALUE"', NATIVE_TYPE 'DATE'),
	TIMEVALUE time OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMEVALUE"', NATIVE_TYPE 'TIME'),
	TIMESTAMPVALUE timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP' OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMESTAMPVALUE"', NATIVE_TYPE 'TIMESTAMP'),
	BOOLEANVALUE boolean OPTIONS (ANNOTATION '', NAMEINSOURCE '"BOOLEANVALUE"', NATIVE_TYPE 'BIT'),
	CHARVALUE string(1) OPTIONS (ANNOTATION '', NAMEINSOURCE '"CHARVALUE"', NATIVE_TYPE 'CHAR'),
	SHORTVALUE integer OPTIONS (ANNOTATION '', NAMEINSOURCE '"SHORTVALUE"', NATIVE_TYPE 'SMALLINT'),
	BIGINTEGERVALUE bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGINTEGERVALUE"', NATIVE_TYPE 'DECIMAL'),
	BIGDECIMALVALUE bigdecimal(15,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGDECIMALVALUE"', NATIVE_TYPE 'DECIMAL'),
	OBJECTVALUE blob(65535) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECTVALUE"', NATIVE_TYPE 'BLOB')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."mediumb"', UPDATABLE TRUE);

CREATE FOREIGN TABLE "bqt2.plan_table" (
	STATEMENT_ID string(30) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STATEMENT_ID"', NATIVE_TYPE 'VARCHAR'),
	"TIMESTAMP" date OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMESTAMP"', NATIVE_TYPE 'DATE'),
	REMARKS string(80) OPTIONS (ANNOTATION '', NAMEINSOURCE '"REMARKS"', NATIVE_TYPE 'VARCHAR'),
	OPERATION string(30) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OPERATION"', NATIVE_TYPE 'VARCHAR'),
	"OPTIONS" string(255) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OPTIONS"', NATIVE_TYPE 'VARCHAR'),
	OBJECT_NODE string(128) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECT_NODE"', NATIVE_TYPE 'VARCHAR'),
	OBJECT_OWNER string(30) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECT_OWNER"', NATIVE_TYPE 'VARCHAR'),
	OBJECT_NAME string(30) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECT_NAME"', NATIVE_TYPE 'VARCHAR'),
	OBJECT_INSTANCE bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECT_INSTANCE"', NATIVE_TYPE 'DECIMAL'),
	OBJECT_TYPE string(30) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECT_TYPE"', NATIVE_TYPE 'VARCHAR'),
	OPTIMIZER string(255) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OPTIMIZER"', NATIVE_TYPE 'VARCHAR'),
	SEARCH_COLUMNS bigdecimal(10,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"SEARCH_COLUMNS"', NATIVE_TYPE 'DECIMAL'),
	ID bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"ID"', NATIVE_TYPE 'DECIMAL'),
	PARENT_ID bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"PARENT_ID"', NATIVE_TYPE 'DECIMAL'),
	POSITION bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"POSITION"', NATIVE_TYPE 'DECIMAL'),
	COST bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"COST"', NATIVE_TYPE 'DECIMAL'),
	CARDINALITY bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"CARDINALITY"', NATIVE_TYPE 'DECIMAL'),
	BYTES bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BYTES"', NATIVE_TYPE 'DECIMAL'),
	OTHER_TAG string(255) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OTHER_TAG"', NATIVE_TYPE 'VARCHAR'),
	PARTITION_START string(255) OPTIONS (ANNOTATION '', NAMEINSOURCE '"PARTITION_START"', NATIVE_TYPE 'VARCHAR'),
	PARTITION_STOP string(255) OPTIONS (ANNOTATION '', NAMEINSOURCE '"PARTITION_STOP"', NATIVE_TYPE 'VARCHAR'),
	PARTITION_ID bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"PARTITION_ID"', NATIVE_TYPE 'DECIMAL'),
	OTHER blob OPTIONS (ANNOTATION '', NAMEINSOURCE '"OTHER"', NATIVE_TYPE 'LONGBLOB'),
	DISTRIBUTION string(30) OPTIONS (ANNOTATION '', NAMEINSOURCE '"DISTRIBUTION"', NATIVE_TYPE 'VARCHAR'),
	CPU_COST bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"CPU_COST"', NATIVE_TYPE 'DECIMAL'),
	IO_COST bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"IO_COST"', NATIVE_TYPE 'DECIMAL'),
	TEMP_SPACE bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"TEMP_SPACE"', NATIVE_TYPE 'DECIMAL'),
	ACCESS_PREDICATES string OPTIONS (ANNOTATION '', NAMEINSOURCE '"ACCESS_PREDICATES"', NATIVE_TYPE 'VARCHAR'),
	FILTER_PREDICATES string OPTIONS (ANNOTATION '', NAMEINSOURCE '"FILTER_PREDICATES"', NATIVE_TYPE 'VARCHAR')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."plan_table"', UPDATABLE TRUE);

CREATE FOREIGN TABLE "bqt2.scalardata" (
	INTKEY bigdecimal(10,2147483647) NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTKEY"', NATIVE_TYPE 'DECIMAL'),
	STRINGKEY string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGKEY"', NATIVE_TYPE 'VARCHAR'),
	INTNUM bigdecimal(11,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTNUM"', NATIVE_TYPE 'DECIMAL'),
	STRINGNUM string(255) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGNUM"', NATIVE_TYPE 'VARCHAR'),
	FLOATNUM bigdecimal(15,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"FLOATNUM"', NATIVE_TYPE 'DECIMAL'),
	LONGNUM bigdecimal(22,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"LONGNUM"', NATIVE_TYPE 'DECIMAL'),
	DOUBLENUM bigdecimal(15,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"DOUBLENUM"', NATIVE_TYPE 'DECIMAL'),
	BYTENUM bigdecimal(3,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BYTENUM"', NATIVE_TYPE 'DECIMAL'),
	DATEVALUE date OPTIONS (ANNOTATION '', NAMEINSOURCE '"DATEVALUE"', NATIVE_TYPE 'DATE'),
	TIMEVALUE time OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMEVALUE"', NATIVE_TYPE 'TIME'),
	TIMESTAMPVALUE timestamp OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMESTAMPVALUE"', NATIVE_TYPE 'DATETIME'),
	BOOLEANVALUE bigdecimal(1,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BOOLEANVALUE"', NATIVE_TYPE 'DECIMAL'),
	CHARVALUE string(1) OPTIONS (ANNOTATION '', NAMEINSOURCE '"CHARVALUE"', NATIVE_TYPE 'CHAR'),
	SHORTVALUE bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"SHORTVALUE"', NATIVE_TYPE 'DECIMAL'),
	BIGINTEGERVALUE bigdecimal(28,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGINTEGERVALUE"', NATIVE_TYPE 'DECIMAL'),
	BIGDECIMALVALUE bigdecimal(15,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGDECIMALVALUE"', NATIVE_TYPE 'DECIMAL'),
	OBJECTVALUE string(2048) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECTVALUE"', NATIVE_TYPE 'VARCHAR')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."scalardata"', UPDATABLE TRUE);

CREATE FOREIGN TABLE "bqt2.smalla" (
	INTKEY long NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTKEY"', NATIVE_TYPE 'INT'),
	STRINGKEY string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGKEY"', NATIVE_TYPE 'VARCHAR'),
	INTNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTNUM"', NATIVE_TYPE 'INT'),
	STRINGNUM string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGNUM"', NATIVE_TYPE 'VARCHAR'),
	FLOATNUM float OPTIONS (ANNOTATION '', NAMEINSOURCE '"FLOATNUM"', NATIVE_TYPE 'FLOAT'),
	LONGNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"LONGNUM"', NATIVE_TYPE 'BIGINT'),
	DOUBLENUM double OPTIONS (ANNOTATION '', NAMEINSOURCE '"DOUBLENUM"', NATIVE_TYPE 'DOUBLE'),
	BYTENUM bigdecimal(8,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BYTENUM"', NATIVE_TYPE 'DECIMAL'),
	DATEVALUE date OPTIONS (ANNOTATION '', NAMEINSOURCE '"DATEVALUE"', NATIVE_TYPE 'DATE'),
	TIMEVALUE time OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMEVALUE"', NATIVE_TYPE 'TIME'),
	TIMESTAMPVALUE timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP' OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMESTAMPVALUE"', NATIVE_TYPE 'TIMESTAMP'),
	BOOLEANVALUE boolean OPTIONS (ANNOTATION '', NAMEINSOURCE '"BOOLEANVALUE"', NATIVE_TYPE 'BIT'),
	CHARVALUE string(1) OPTIONS (ANNOTATION '', NAMEINSOURCE '"CHARVALUE"', NATIVE_TYPE 'CHAR'),
	SHORTVALUE integer OPTIONS (ANNOTATION '', NAMEINSOURCE '"SHORTVALUE"', NATIVE_TYPE 'SMALLINT'),
	BIGINTEGERVALUE bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGINTEGERVALUE"', NATIVE_TYPE 'DECIMAL'),
	BIGDECIMALVALUE bigdecimal(15,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGDECIMALVALUE"', NATIVE_TYPE 'DECIMAL'),
	OBJECTVALUE blob(65535) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECTVALUE"', NATIVE_TYPE 'BLOB')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."smalla"', UPDATABLE TRUE);

CREATE FOREIGN TABLE "bqt2.smallb" (
	INTKEY long NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTKEY"', NATIVE_TYPE 'INT'),
	STRINGKEY string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGKEY"', NATIVE_TYPE 'VARCHAR'),
	INTNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTNUM"', NATIVE_TYPE 'INT'),
	STRINGNUM string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGNUM"', NATIVE_TYPE 'VARCHAR'),
	FLOATNUM float OPTIONS (ANNOTATION '', NAMEINSOURCE '"FLOATNUM"', NATIVE_TYPE 'FLOAT'),
	LONGNUM long OPTIONS (ANNOTATION '', NAMEINSOURCE '"LONGNUM"', NATIVE_TYPE 'BIGINT'),
	DOUBLENUM double OPTIONS (ANNOTATION '', NAMEINSOURCE '"DOUBLENUM"', NATIVE_TYPE 'DOUBLE'),
	BYTENUM bigdecimal(8,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BYTENUM"', NATIVE_TYPE 'DECIMAL'),
	DATEVALUE date OPTIONS (ANNOTATION '', NAMEINSOURCE '"DATEVALUE"', NATIVE_TYPE 'DATE'),
	TIMEVALUE time OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMEVALUE"', NATIVE_TYPE 'TIME'),
	TIMESTAMPVALUE timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP' OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMESTAMPVALUE"', NATIVE_TYPE 'TIMESTAMP'),
	BOOLEANVALUE boolean OPTIONS (ANNOTATION '', NAMEINSOURCE '"BOOLEANVALUE"', NATIVE_TYPE 'BIT'),
	CHARVALUE string(1) OPTIONS (ANNOTATION '', NAMEINSOURCE '"CHARVALUE"', NATIVE_TYPE 'CHAR'),
	SHORTVALUE integer OPTIONS (ANNOTATION '', NAMEINSOURCE '"SHORTVALUE"', NATIVE_TYPE 'SMALLINT'),
	BIGINTEGERVALUE bigdecimal(38,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGINTEGERVALUE"', NATIVE_TYPE 'DECIMAL'),
	BIGDECIMALVALUE bigdecimal(15,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGDECIMALVALUE"', NATIVE_TYPE 'DECIMAL'),
	OBJECTVALUE blob(65535) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECTVALUE"', NATIVE_TYPE 'BLOB')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."smallb"', UPDATABLE TRUE);

CREATE FOREIGN TABLE "bqt2.splitparttxn1" (
	COLUMN1 bigdecimal(38,2147483647) NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"COLUMN1"', NATIVE_TYPE 'DECIMAL'),
	JOINCOLUMN1 bigdecimal(38,2147483647) NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"JOINCOLUMN1"', NATIVE_TYPE 'DECIMAL')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."splitparttxn1"', UPDATABLE TRUE);

CREATE FOREIGN TABLE "bqt2.splitparttxn2" (
	COLUMN2 bigdecimal(38,2147483647) NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"COLUMN2"', NATIVE_TYPE 'DECIMAL'),
	JOINCOLUMN2 bigdecimal(38,2147483647) NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"JOINCOLUMN2"', NATIVE_TYPE 'DECIMAL')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."splitparttxn2"', UPDATABLE TRUE);

CREATE FOREIGN TABLE "bqt2.tinya" (
	INTKEY bigdecimal(22,2147483647) NOT NULL DEFAULT '' OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTKEY"', NATIVE_TYPE 'DECIMAL'),
	STRINGKEY string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGKEY"', NATIVE_TYPE 'VARCHAR'),
	INTNUM bigdecimal(22,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"INTNUM"', NATIVE_TYPE 'DECIMAL'),
	STRINGNUM string(10) OPTIONS (ANNOTATION '', NAMEINSOURCE '"STRINGNUM"', NATIVE_TYPE 'VARCHAR'),
	FLOATNUM bigdecimal(15,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"FLOATNUM"', NATIVE_TYPE 'DECIMAL'),
	LONGNUM bigdecimal(28,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"LONGNUM"', NATIVE_TYPE 'DECIMAL'),
	DOUBLENUM bigdecimal(28,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"DOUBLENUM"', NATIVE_TYPE 'DECIMAL'),
	BYTENUM bigdecimal(8,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BYTENUM"', NATIVE_TYPE 'DECIMAL'),
	DATEVALUE date OPTIONS (ANNOTATION '', NAMEINSOURCE '"DATEVALUE"', NATIVE_TYPE 'DATE'),
	TIMEVALUE time OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMEVALUE"', NATIVE_TYPE 'TIME'),
	TIMESTAMPVALUE timestamp OPTIONS (ANNOTATION '', NAMEINSOURCE '"TIMESTAMPVALUE"', NATIVE_TYPE 'DATETIME'),
	BOOLEANVALUE bigdecimal(1,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BOOLEANVALUE"', NATIVE_TYPE 'DECIMAL'),
	CHARVALUE string(1) OPTIONS (ANNOTATION '', NAMEINSOURCE '"CHARVALUE"', NATIVE_TYPE 'CHAR'),
	SHORTVALUE bigdecimal(8,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"SHORTVALUE"', NATIVE_TYPE 'DECIMAL'),
	BIGINTEGERVALUE bigdecimal(28,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGINTEGERVALUE"', NATIVE_TYPE 'DECIMAL'),
	BIGDECIMALVALUE bigdecimal(15,2147483647) OPTIONS (ANNOTATION '', NAMEINSOURCE '"BIGDECIMALVALUE"', NATIVE_TYPE 'DECIMAL'),
	OBJECTVALUE string(2048) OPTIONS (ANNOTATION '', NAMEINSOURCE '"OBJECTVALUE"', NATIVE_TYPE 'VARCHAR')
) OPTIONS (ANNOTATION '', NAMEINSOURCE '"bqt2"."tinya"', UPDATABLE TRUE);